config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my', controllers: {
      sessions:'users/sessions', registrations:'users/registrations', confirmations:'users/confirmations',
      mailer:'users/mailer', passwords:'users/passwords', shared:'users/shared', unlocks:'users/unlocks', users:'users/AdminActions'
  }

  resources :users

  resources :courses do
    resources :projects
  end

  resources :users do
    resources :enrollment
  end

  resources :projects do
    resources :teams
    resources :ratings
  end

  resources :teams do
      resources :team_memberships
      resources :ratings
  end

  resources :ratings do
    resources :users
  end


  resources :team_memberships do
    resources :ratings
  end



  resources :universities
  resources :semesters
  resources :teacher
  # resources :enrollment
  # resources :ratings, :except => [:new]



  get 'welcome/index'
  root 'welcome#index'
  get 'myprofile' => 'users#myProfile'
  get '/admin/userlist' => 'admin#adminList'
  get '/admin' => 'admin#adminDash'
  get 'users/:id' => 'users#show', :as => 'show_user'
  get 'teacherportal' => 'courses#teacherPortal'
  get 'enrollme/:user_id' => 'enrollment#new'
  get 'myclasses' => 'courses#myclasses'
  get 'admin/edit/:id' => 'users#adminEdit', :as => 'admin_edit'
  get 'admin/resetpassword/:id' => 'users#passwordReset', :as => 'admin_password_reset'
  get 'admin/enrollment' => 'enrollment#adminNew'
  # get 'ratings/:team_id/:user_id/new' => 'ratings#new', :as => 'new_rating'
  patch 'admin/:id/togApp' => 'users#toggleApproved', :as => 'togApp'
  patch 'admin/:id/togSA' => 'users#toggleSuperAdmin', :as => 'togSA'
  patch 'admin/:id/togIns' => 'users#toggleInstructor', :as => 'togIns'
  patch 'admin/:id/togOrgAd' => 'users#toggleOrgAdmin', :as => 'togOA'
  patch 'admin/:id/togStudent' => 'users#toggleStudent', :as => 'togStu'
  post 'banStudent/:cid/:sid' => 'enrollment#toggleBan', :as => 'banStudent'
  post 'unenroll/:cid/:sid' => 'enrollment#unEnroll', :as => 'removeEnrollment'
  post 'team/:team_id/team_memberships' => 'team_memberships#joinGroup', :as => 'team_joinGroup'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/semester.rb
class Semester < ApplicationRecord
  # has_one :university, foreign_key: :uni_id
  # belongs_to :university, foreign_key: :uni_id, optional: true
  has_many :courses
  has_many :projects
  before_create :randomize_id


  private

  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Semester.where(id: self.id).exists?
  end


end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  after_action :verify_authorized

  #Generates a new semester
  def new
    @user = current_user
    @semester = Semester.new
    authorize @semester
    semList
  end

  # Creates the new semester and fills in the information needed
  def create
    @semester = Semester.new(semester_params)
    authorize @semester
    if @semester.save
      redirect_back(fallback_location: root_path)
    else
      render 'new'
    end
  end

  def destroy
    @semester = Semester.find(params[:id])
    authorize @semester
    @semester.destroy
    redirect_to '/admin'
  end

  # # Generates the list of all the possible semesters
  def semList
    @semesters = Semester.all
    authorize @semester
  end

  # Allows user to edit the specific semester
  def edit
    @semester = Semester.find(params[:id])
    authorize @semester
  end

  # Allows the user to update the semester information
  def update
    @semester = Semester.find(params[:id])
    authorize @semester
    if @semester.update(semester_params)
      redirect_back(fallback_location: root_path)
    else
      render 'edit'
    end
  end




  private

  def semester_params
    params.require(:semester).permit([:name, :beginDate, :endDate, :university_id])
  end

end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/edit.html.erb
<%= form_for @semester do |f| %>
  <%= f.label "Semester Name" %><br>
  <%= f.text_field :name %><br>

  <%= f.label "Begin Date" %>
  <%= datepicker_input(f, :beginDate) %>

  <%= f.label "End Date" %>
  <%= datepicker_input(f, :endDate) %>

  <div class="field">
    <%= f.label 'University'%>
    <%= f.select(:university_id, University.all.pluck(:uniName, :id)) %>
  </div>

  <%= f.submit "Update Semester" %>


<% end %>

app/views/semesters/new.html.erb
<%= form_for @semester do |f| %>
  <%= f.label "Semester Name" %><br>
  <%= f.text_field :name %><br>

  <%= f.label "Begin Date" %>
  <%= datepicker_input(f, :beginDate) %>

  <%= f.label "End Date" %>
  <%= datepicker_input(f, :endDate) %>

  <% if current_user.SuperAdmin? %>
    <div class="field">
      <%= f.label 'University'%>
      <%= f.select(:university_id, University.all.pluck(:uniName, :id)) %>
    </div>

  <% else %>
      <%= f.label 'University'%>
      <%= f.select(:university_id, University.where('universities.id = ? ', current_user.university_id ).pluck(:uniName, :id)) %>
  <% end %>
  <%= f.submit "Create Semester" %>
<% end %><br>

<table>
  <th>Semester</th>
  <th>Options</th>
  <% @semesters.each do |semester| %>
    <tr>
      <td><%= semester.name %></td>
      <td>
        <%= link_to "Edit", edit_semester_path(semester) %><br>
        <%= link_to "Delete", semester_path(semester), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>