config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my', controllers: {
      sessions:'users/sessions', registrations:'users/registrations', confirmations:'users/confirmations',
      mailer:'users/mailer', passwords:'users/passwords', shared:'users/shared', unlocks:'users/unlocks', users:'users/AdminActions'
  }

  resources :users

  resources :courses do
    resources :projects
  end

  resources :users do
    resources :enrollment
  end

  resources :projects do
    resources :teams
    resources :ratings
  end

  resources :teams do
      resources :team_memberships
      resources :ratings
  end

  resources :ratings do
    resources :users
  end


  resources :team_memberships do
    resources :ratings
  end



  resources :universities
  resources :semesters
  resources :teacher
  # resources :enrollment
  # resources :ratings, :except => [:new]



  get 'welcome/index'
  root 'welcome#index'
  get 'myprofile' => 'users#myProfile'
  get '/admin/userlist' => 'admin#adminList'
  get '/admin' => 'admin#adminDash'
  get 'users/:id' => 'users#show', :as => 'show_user'
  get 'teacherportal' => 'courses#teacherPortal'
  get 'enrollme/:user_id' => 'enrollment#new'
  get 'myclasses' => 'courses#myclasses'
  get 'admin/edit/:id' => 'users#adminEdit', :as => 'admin_edit'
  get 'admin/resetpassword/:id' => 'users#passwordReset', :as => 'admin_password_reset'
  get 'admin/enrollment' => 'enrollment#adminNew'
  # get 'ratings/:team_id/:user_id/new' => 'ratings#new', :as => 'new_rating'
  patch 'admin/:id/togApp' => 'users#toggleApproved', :as => 'togApp'
  patch 'admin/:id/togSA' => 'users#toggleSuperAdmin', :as => 'togSA'
  patch 'admin/:id/togIns' => 'users#toggleInstructor', :as => 'togIns'
  patch 'admin/:id/togOrgAd' => 'users#toggleOrgAdmin', :as => 'togOA'
  patch 'admin/:id/togStudent' => 'users#toggleStudent', :as => 'togStu'
  post 'banStudent/:cid/:sid' => 'enrollment#toggleBan', :as => 'banStudent'
  post 'unenroll/:cid/:sid' => 'enrollment#unEnroll', :as => 'removeEnrollment'
  post 'team/:team_id/team_memberships' => 'team_memberships#joinGroup', :as => 'team_joinGroup'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_adminNav.html.erb
<div id="adminNav">

  <a>
    <form action="admin/userlist">
      <input type="submit" value="User List"/>
    </form>

    <form action="universities/new">
      <input type="submit" id ="newUni" value="New University"/>
    </form>
    
    <form action="semesters/new">
      <input type="submit" value="New Semester"/>
    </form>
  </a>

</div>

app/views/admin/adminDash.html.erb
<h2>Admin Portal</h2>
<%= render 'adminNav' %>

app/views/admin/adminEdit.html.erb
<!--<h2>Edit <%#= resource_name.to_s %></h2>-->

<%= form_for @user do |f|%>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/admin/adminList.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Student?</th>
      <th>Instructor?</th>
      <th>Organization Admin?</th>
      <th>Super Admin</th>
      <th>Approved</th>
      <th>Links</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% if (current_user.university_id == user.university_id and current_user.OrgAdmin?) or  current_user.SuperAdmin? %>
          <tr>
            <td><%= user.email%></td>
            <td><%= user.firstName %></td>
            <td><%= user.lastName %></td>
            <td>
              <% if user.Student? %>
                <%= button_to 'True', togStu_path(user), method: :patch %>
              <% else %>
                <%= button_to 'False', togStu_path(user), method: :patch %>
              <%end %>
            </td>
            <td>
              <% if user.Instructor? %>
                <%= button_to 'True', togIns_path(user), method: :patch %>
              <% else %>
                <%= button_to 'False', togIns_path(user), method: :patch %>
              <%end %>
            </td>
            <td>
              <% if user.OrgAdmin? %>
                <%= button_to 'True', togOA_path(user), method: :patch %>
              <% else %>
                <%= button_to 'False', togOA_path(user), method: :patch %>
              <%end %>
            </td>
            <td>
              <% if user.SuperAdmin? %>
                <%= button_to 'True', togSA_path(user), method: :patch %>
              <% else %>
                <%= button_to 'False', togSA_path(user), method: :patch %>
              <%end %>
            </td>
            <td>
              <% if user.approved? %>
                <%= button_to 'True', togApp_path(user), method: :patch %>
              <% else %>
                <%= button_to 'False', togApp_path(user), method: :patch %>
              <%end %>
            </td>
            <td>
              <%=link_to 'Show', show_user_path(user) %><br>
              <%= link_to 'Edit', admin_edit_path(user) %><br>
              <%= link_to "Reset Password", admin_password_reset_path(user)%>

            </td>

          </tr>
      <% end %>
        <%end %>
    </tbody>
  </table>
</div>