config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my', controllers: {
      sessions:'users/sessions', registrations:'users/registrations', confirmations:'users/confirmations',
      mailer:'users/mailer', passwords:'users/passwords', shared:'users/shared', unlocks:'users/unlocks', users:'users/AdminActions'
  }

  resources :users

  resources :courses do
    resources :projects
  end

  resources :users do
    resources :enrollment
  end

  resources :projects do
    resources :teams
    resources :ratings
  end

  resources :teams do
      resources :team_memberships
      resources :ratings
  end

  resources :ratings do
    resources :users
  end


  resources :team_memberships do
    resources :ratings
  end



  resources :universities
  resources :semesters
  resources :teacher
  # resources :enrollment
  # resources :ratings, :except => [:new]



  get 'welcome/index'
  root 'welcome#index'
  get 'myprofile' => 'users#myProfile'
  get '/admin/userlist' => 'admin#adminList'
  get '/admin' => 'admin#adminDash'
  get 'users/:id' => 'users#show', :as => 'show_user'
  get 'teacherportal' => 'courses#teacherPortal'
  get 'enrollme/:user_id' => 'enrollment#new'
  get 'myclasses' => 'courses#myclasses'
  get 'admin/edit/:id' => 'users#adminEdit', :as => 'admin_edit'
  get 'admin/resetpassword/:id' => 'users#passwordReset', :as => 'admin_password_reset'
  get 'admin/enrollment' => 'enrollment#adminNew'
  # get 'ratings/:team_id/:user_id/new' => 'ratings#new', :as => 'new_rating'
  patch 'admin/:id/togApp' => 'users#toggleApproved', :as => 'togApp'
  patch 'admin/:id/togSA' => 'users#toggleSuperAdmin', :as => 'togSA'
  patch 'admin/:id/togIns' => 'users#toggleInstructor', :as => 'togIns'
  patch 'admin/:id/togOrgAd' => 'users#toggleOrgAdmin', :as => 'togOA'
  patch 'admin/:id/togStudent' => 'users#toggleStudent', :as => 'togStu'
  post 'banStudent/:cid/:sid' => 'enrollment#toggleBan', :as => 'banStudent'
  post 'unenroll/:cid/:sid' => 'enrollment#unEnroll', :as => 'removeEnrollment'
  post 'team/:team_id/team_memberships' => 'team_memberships#joinGroup', :as => 'team_joinGroup'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_userLogin.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
<div class = "login">
  <h2>Sign In</h2>
  <%= f.label :email%>
  <%= f.text_field :email%> <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <ul id = "todd">
  <li><%= f.check_box :remember_me %><%= f.label :remember_me %></li>
  </ul>
  <%= f.submit 'Sign in' %>
 
  <%= link_to "Sign Up", new_user_registration_path %>
<!--  <%#= link_to "Forgot your password?", new_password_path(:user) %><br>-->
   </div>
<% end %>

app/views/welcome/_userNav.html.erb
<body>
<table class="table">
  <thead>
  <% if current_user.approved? %>
      <th>
        <form action="myprofile">
        <input type="submit" value="My Profile"/>
        </form>
      </th>
    <% if current_user.Student? %>
      <th>
          <form action="myclasses">
          <input type="submit" value="My Classes"/>
          </form>
        </th>
        <th>
          <form action=<%= "enrollme/#{current_user.id}" %>>
            <input type="submit" value="Enroll in a course"/>
          </form>
        </th>
    <% end %>
    <% if current_user.Instructor? %>
        <th>
          <form action="teacherportal">
            <input type="submit" value="Teacher Portal"/>
          </form>
        </th>
    <% end %>
    <% if current_user.SuperAdmin? or current_user.OrgAdmin? %>
      <th>
          <form action="admin">
            <input type="submit" value="Admin Portal"/>
          </form>
      </th>
    <% end %>
  <% else %>
    <h1>Get an admin to approve your account to begin using CollaboRATE</h1>
  <% end %>
  </thead>
  <tbody>
  </tbody>
</table>



</body>

app/views/welcome/index.html.erb
<body>
  <% if not user_signed_in? %>
    <div id="formWrapper" class="row">
      <%= render 'userLogin' %>
    </div>
  <% else %>
    <h1>My Dashboard</h1>
    <div class="row">
      <%= render 'userNav' %>
  <% end %>
    </div>
<!--  </div>-->
</body>

app/views/welcome/profile.html.erb
<header>
  <div id="buttonWrapper">
    <% if not user_signed_in? %>
      You are not signed in
    <% else %>
      Hello, <%= current_user.firstName %>!
      <%= link_to('Sign out', destroy_user_session_path, method: :delete) %>
    <% end %>
  </div>
</header>

<body>
    <img src = "../assets/images/kid yelling.jpg" alt="Screaming child">
    
    
    
    
</body>