config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my', controllers: {
      sessions:'users/sessions', registrations:'users/registrations', confirmations:'users/confirmations',
      mailer:'users/mailer', passwords:'users/passwords', shared:'users/shared', unlocks:'users/unlocks', users:'users/AdminActions'
  }

  resources :users

  resources :courses do
    resources :projects
  end

  resources :users do
    resources :enrollment
  end

  resources :projects do
    resources :teams
    resources :ratings
  end

  resources :teams do
      resources :team_memberships
      resources :ratings
  end

  resources :ratings do
    resources :users
  end


  resources :team_memberships do
    resources :ratings
  end



  resources :universities
  resources :semesters
  resources :teacher
  # resources :enrollment
  # resources :ratings, :except => [:new]



  get 'welcome/index'
  root 'welcome#index'
  get 'myprofile' => 'users#myProfile'
  get '/admin/userlist' => 'admin#adminList'
  get '/admin' => 'admin#adminDash'
  get 'users/:id' => 'users#show', :as => 'show_user'
  get 'teacherportal' => 'courses#teacherPortal'
  get 'enrollme/:user_id' => 'enrollment#new'
  get 'myclasses' => 'courses#myclasses'
  get 'admin/edit/:id' => 'users#adminEdit', :as => 'admin_edit'
  get 'admin/resetpassword/:id' => 'users#passwordReset', :as => 'admin_password_reset'
  get 'admin/enrollment' => 'enrollment#adminNew'
  # get 'ratings/:team_id/:user_id/new' => 'ratings#new', :as => 'new_rating'
  patch 'admin/:id/togApp' => 'users#toggleApproved', :as => 'togApp'
  patch 'admin/:id/togSA' => 'users#toggleSuperAdmin', :as => 'togSA'
  patch 'admin/:id/togIns' => 'users#toggleInstructor', :as => 'togIns'
  patch 'admin/:id/togOrgAd' => 'users#toggleOrgAdmin', :as => 'togOA'
  patch 'admin/:id/togStudent' => 'users#toggleStudent', :as => 'togStu'
  post 'banStudent/:cid/:sid' => 'enrollment#toggleBan', :as => 'banStudent'
  post 'unenroll/:cid/:sid' => 'enrollment#unEnroll', :as => 'removeEnrollment'
  post 'team/:team_id/team_memberships' => 'team_memberships#joinGroup', :as => 'team_joinGroup'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :course
  belongs_to :user, optional: true
  belongs_to :semester, optional: true
  has_many :teams, dependent: :destroy
  has_many :ratings, dependent: :destroy
  before_save :saveActions
  before_create :createActions
  before_create :randomize_id


  def saveActions
    # self.semester_id = :course.semester_id
    # self.user_id = :user.id

  end

  def createActions

  end


  private
  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000)
    end while Project.where(id: self.id).exists?
  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  after_action :verify_authorized

  #
  def new
    @course = Course.find(params[:course_id])
    @project = @course.projects.new
    authorize @project
  end

  # Creates a project and fills in the information needed such as the creator of the project, the course it's for,
  # and the semester
  def create
    @course = Course.find(params[:course_id])
    @project = @course.projects.create(projectParams)
    authorize @project
    @user = current_user
    @project.user_id = @user.id
    @project.semester_id = @project.semester_id
    if @project.save
      ActiveRecord::Base.transaction do
        @project.numGroups.times do |n|
          Team.create!(project_id: @project.id, groupNum:n+1, course_id: @project.course_id)
        end
        end
        redirect_to course_path(@course)
    else
      flash[:Alert] = "Could not save Project"
      redirect_back(fallback_location: root_path)
      end
  end

  def destroy
    @course = Course.find(params[:course_id])
    @project = @course.projects.find(params[:id])
    authorize @project
    @project.destroy
    redirect_to course_path(@course)
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  def edit
    @course = Course.find(params[:course_id])
    @project = @course.projects.find(params[:id])
    authorize @project
  end

  def update
    @project = Project.find(params[:id])
    authorize @project
    if @project.update(projectParams)
      redirect_to course_path(@project.course_id)
    else
      render 'edit'
    end
  end



  private

  def projectParams
    params.require(:project).permit(:name, :semester_id, :user_id, :course_id, :numGroups, :availableDate, :dueDate)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_rating_option.html.erb
<%= link_to "Rate User", new_team_membership_rating_path(:t) %>

app/views/projects/_student_group.html.erb
<% current_user.myTeams(@project).each do |f| %>
  <strong>Group <%= f.groupNum %></strong><br>
  <%= "You may begin rating your groupmates on #{@project.dueDate+1}. All ratings must be submitted by #{@project.dueDate+8}" %><br>
  <table class="table">
    <thead>
    <th>Name</th>
    <th>Email</th>
    <th>CollaboRATING</th>
    <% if Date.today >= @project.dueDate + 1 and Date.today <= @project.dueDate + 8 %>
      <th>Options</th>
    <% end %>
    </thead>
    <tbody>
    <% f.team_memberships.each do |t| %>
      <tr>
        <td><%= t.user.fullName %></td>
        <td><%= t.user.email %></td>
        <td>
          <% if t.user.numRatings > 0 %>
            <%= t.user.getRatings %>
          <% else %>
            Not Yet Rated
          <% end %>
        </td>

          <% if Date.today >= @project.dueDate + 1 and Date.today <= @project.dueDate + 8 %>
          <td>
            <%# if not t.user.getRatings.where('ratings.user_id = ? and ratings.created_by = ? and ratings.project_id = ?', t.user.id, current_user.id, t.project_id).present? and current_user.id != t.user.id %>
            <% if t.user.hasRated(t.user_id, current_user.id, @project.id) == 0 and current_user.id != t.user_id %>
              <%= link_to "Rate User", new_team_membership_rating_path(t) %>
            <% elsif current_user.id == t.user.id %>
              You cannot rate yourself :)
            <% else %>
              You've already rated this student
            <% end %>
          </td>
          <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to "Back to Class", course_path(@project.course_id) %><br>

app/views/projects/_teacher_project_view.html.erb
<table class="table">
  <thead>
    <th>Rating For</th>
    <th>Created By</th>
    <th>Rating</th>
    <th>Options</th>
  </thead>
  <tbody>
    <% @project.ratings.order(:user_id).each do |r| %>
      <% if r.rating <=2 %>
        <tr style="background-color:yellow; border:2pt solid black;">
      <% else %>
          <tr>
      <% end %>
             <td><%= r.user.fullName %></td>
            <td><%= r.getCreator %></td>
            <td><%= r.rating %></td>
            <td><%= link_to "Delete Rating", rating_path(r), method: :delete %></td>
          </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label "Available date" %><br>
  <%= datepicker_input(f,:availableDate) %><br>
  <%= f.label "Due Date" %>
  <%= datepicker_input(f, :dueDate) %>
  <%= f.submit%>
<% end %>

app/views/projects/new.html.erb
  <%= form_for([@course, @course.projects.build]) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label 'Number of Groups' %><br>
    <%= f.number_field :numGroups,{:value => 1, min:1, step:1} %><br>
    <%= f.label :availableDate %><br>
    <%= datepicker_input(f,:availableDate) %><br>
    <%= f.label :dueDate %>
    <%= datepicker_input(f, :dueDate) %>
    <%= f.submit%>
  <% end %>

app/views/projects/show.html.erb
<h2><%= @project.name %><br></h2>
<% if current_user.hasTeam?(@project) %>
  <%= render 'student_group' %>
<% else %>
  <table class="table">
    <thead>
        <th>Group Number</th>
        <th># of Members</th>
        <th>Options</th>
    </thead>
    <tbody>
    <% @project.teams.sort_by(&:groupNum).each do |t| %>
        <tr>
          <td><%= t.groupNum %></td>
          <td><%= t.team_memberships.count %></td>
          <td>
            <%= link_to "Show", team_path(t.id) %><br>
            <% if Date.today <= @project.dueDate and Date.today >= @project.availableDate %>
              <%= link_to "Join Team", team_joinGroup_path(t), method: :post %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% if current_user.id == @project.course.teacher %>
  <%= render 'teacher_project_view'%>
<% end %>
<%=link_to 'Previous Page', 'javascript:history.back()'%>